### ISSUE TITLE
Can't require gem on RPi 3B+

### ISSUE THREAD

**Issue by egor-khanko** [ClockVapor/rpi_gpio#23]
I am getting an `wrong ELF class: ELFCLASS32` when trying to require gem. Tested on ruby 2.7.0 and 2.5.7

Full output:

> Traceback (most recent call last):
        2: from pwm.rb:1:in `<main>'
        1: from /usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rpi_gpio (LoadError)
        6: from pwm.rb:1:in `<main>'
        5: from /usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        4: from /usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        3: from /usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        2: from /home/egorpr0/.rvm/gems/ruby-2.7.0/gems/rpi_gpio-0.5.0/lib/rpi_gpio.rb:1:in `<top (required)>'
        1: from /usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/share/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': /home/egorpr0/.rvm/gems/ruby-2.7.0/gems/rpi_gpio-0.5.0/lib/rpi_gpio/rpi_gpio.so: wrong ELF class: ELFCLASS32 - /home/egorpr0/.rvm/gems/ruby-2.7.0/gems/rpi_gpio-0.5.0/lib/rpi_gpio/rpi_gpio.so (LoadError)

Happy to perform some testing!

**Comment by egor-khanko** [comment]
Fixed everything by installing 32-bit **Raspberry Pi OS (Raspbian)** instead of 64-bit Ubuntu Server.
32-bit Ubuntu Server also didn't work because you can't access GPIO ports without root permission (maybe you can, but i didn't find it, and it was easier to reinstall OS)
